# Generated by Django 3.0.6 on 2020-05-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
